### ISSUE TITLE
Configurator not loading

### ISSUE THREAD

**Issue by mark-truran** [Labernator/Stargrave#4]
Hi,

I used this app about a month ago and I think it is great. Wonderful UI design.

Now the demo link (https://labernator.github.io/Stargrave/) just loads a blank screen with 404 errors in the console. 

Is this a bug or have you removed the demo on purpose?

Kind regards,

Mark

**Comment by Labernator** [comment]
Hi Mark,
sorry for that!
I was not expecting anyone to actually use this. Me and the two friends I play with are currently running a mordheim campaign, so we more or less forgot about this app.

Glad to hear you like it!

I have pushed the latest changed I did a while ago and reinitialized the demo page.
It might be that the rosters you have created in the past are not compatible with the current version.
I added a lot of functionality at once a while back (creating PDFs, doing post game sequences, moving loot around and selling it, etc.)
If you created your rosters before that change you will unfortunately need to recreate them, since these changes were not backward compatible.

Sorry for any inconveniences I caused you.
When my kids will start to go to bed earlier and sleep more consistently I will update the readme page with a user guide on how to use the different features. Currently I simply don't have the time to spend.

Best regards,
Marius

PS: If you find any inconsistencies, bugs or missing features, feel free to report them. I will try to do my best to fix them :)

**Comment by mark-truran** [comment]
Hi Marius,

Thanks for your help. I have just used the app and it is working fine now. I think it is really impressive. My friends and I are all putting crews together. I'll raise any issues we come across. Good luck with the Mordheim campaign. I love that game :)

Mark
