### ISSUE TITLE
PDF export overflows first page

### ISSUE THREAD

**Issue by mark-truran** [Labernator/Stargrave#5]
Hi,

First of all, I love this app so much. I don't understand why everyone isn't using it. Thanks for making it.

Second, I have an issue when exporting to PDF. The last two soldiers are overflowing the bottom of the page.

![image](https://user-images.githubusercontent.com/13332188/197848745-93a42efc-865f-405e-93cc-9c30d94aa94e.png)

Are you also seeing this?

Kind regards,

Mark

**Comment by Labernator** [comment]
Hi Mark,

glad you like it :) 
It is a lot of copy right infringement from my end, since I do not own the images. So I just hope I don't get in trouble and have to take it down.

I will have a look into it and see if I can reproduce it with a random crew, but could you add the crew .json here? That would help a lot in issue reproduction.

Thanks and best regards,
Marius

**Comment by mark-truran** [comment]
Hi Marius,

Sorry for the delay. I have been busy painting models and scenery :)

I will post a link to the file. One sec.

Kind regards,

Mark

**Comment by mark-truran** [comment]
I've put it on Google drive:

https://drive.google.com/file/d/11Ntn6PVPbPcaUHSvA-oLvd3m86Ic8ve2/view?usp=sharing

Let me know if I can do anything to help.

**Comment by Labernator** [comment]
Hi Mark,

I have updated the code accordingly and it should now work.
Instead of putting everything on one page, I split to two pages (Heroes and Goons) if there are more than 5 soldiers.

I hope this is to your liking. If you would like/expected something different, please let me know.

**Comment by mark-truran** [comment]
Hi Marius,

I just tried it out. It looks great.

Thanks for your hard work!

Kind regards,

Mark
